### ISSUE TITLE
School data

### ISSUE THREAD

**Issue by mhchayan** [msmobility/mito#108]
Is it possible to run this model without school data? Thanks.

-Mahmudul

**Comment by nkuehnel** [comment]
Hi Mahmudul,

in principle, yes. However, in this case, the destination of HBE (education) trips cannot be defined by the synthetic population. In addition, the attraction variable for the destination choice model is the total number of school places in a given zone. This means that the distribution of HBE trips will be dependent on the travel impedance only. The destination choice model follows the formulation described here: https://tfresource.org/topics/Destination_Choice_Mathematical_Formulation.html
