### ISSUE TITLE
Adjust Travel Time Budget and Trip Generation for MiD data

### ISSUE THREAD

**Issue by nkuehnel** [msmobility/mito#16]
in MiD data 1 home based trip considers the way back, too. So we need to create two Mito trips for each.

**Comment by moeckel** [comment]
The conversion from one round-trip (as it should be handled in trip generation, trip distribution and mode choice) to one outbound and one return trip should happen in the time-of-day choice model.

**Comment by nkuehnel** [comment]
Notes from 14th February Munich Model Meeting:
- currently trips are generated as single legs not as round trips and therefore sampling in the trip generation generates too many trips
- travel time budget needs to be adjusted accordingly
- also, destination choice should consider round trips for travel time budget adjustments in non mandatory trips

**Comment by nkuehnel** [comment]
has been implemented for some time now.
