### ISSUE TITLE
Look for UEC replacement

### ISSUE THREAD

**Issue by nkuehnel** [msmobility/mito#20]

**Comment by nkuehnel** [comment]
this would:
- get rid of excel parsing problems because of different system locales ("." and "," decimal delimiters)
- get rid of proprietary excel format
- get rid of a (not fully open source?) maven dependency
- maybe improve the speed for setting up the equations

**Comment by nkuehnel** [comment]
one possible solution would be using built-in javascript engine to evaluate expressions defined in a javascript file (resolves at least the first three of mentioned points in the previous comment and is probably also faster)

**Comment by moeckel** [comment]
I like the idea. I certainly would love to get rid of the Excel dependency. My conditions for switching would be:
- Needs to run fast (i.e., at least as fast as what we have implemented right now, which is not particularly fast...)
- Needs to run on any machine without licensing or OS issues (seems to be the case with Javascript)
- Needs to be easy to change parameters and equations (would like to see an example what input files look like)
