### ISSUE TITLE
Too many students without occupation zone

### ISSUE THREAD

**Issue by nkuehnel** [msmobility/mito#33]
Mito currently ignores workers or students in the travel time budget calculation if they dont have a zone assigned as workplace. 

Also, trip destination has to randomly assign hbe trips done by students because no zone is set.

This needs to be fixed on the input level, providing occupation zones for students (like its done for workers)

**Comment by moeckel** [comment]
➤ Ana Tsui Moreno commented:

This issue will be solved with the new version of the synthetic population, on which we will have student school zones.

**Comment by nkuehnel** [comment]
fixed.
