### ISSUE TITLE
Review transit travel times

### ISSUE THREAD

**Issue by moeckel** [msmobility/mito#45]
A) There are o/d pairs with a very low speed for transit.
B) Transit travelers in MITO are slower than MiD transit travelers.
c) Auto travelers in MITO are faster than MiD travelers.

┆Attachments: <a href="https:&#x2F;&#x2F;app.asana.com&#x2F;app&#x2F;asana&#x2F;-&#x2F;download_asset?asset_id&#x3D;609594052716049">hema.pptx</a> | <a href="https:&#x2F;&#x2F;app.asana.com&#x2F;app&#x2F;asana&#x2F;-&#x2F;download_asset?asset_id&#x3D;611128956180434">main.html</a>

**Comment by moeckel** [comment]
➤ Carlos Llorca commented:

With respect of the cloud of points at the top of the plots: 
The unusually higher travel times are associated with very high access and egress times to or from transit stops. Their speed is close to walking speed of 5 km/h. For these o/d pairs travelers rarely chose transit. 

We can: 
1) remove transit travel times from the transit skims when access/egress exceeds certain value, e.g. 1 h. This would delete the points of the top of the plots and assign them NA values, currently converted to time = 1000 mins in MITO.
2) keep access and egress modes as high as the transit assignment finds, so travelers will have a very high travel time for transit options, and will not select it. This will convert our current NA values into actual times by transit with extra-long access or egress. 

Although the result is similar it will not be exactly the same... 

With respect of the cloud of points on the 'normal' interval I cannot make any suggestion yet, since speeds are obviously lower than mid, as we are dividing transit travel times by auto travel distances. But there is no reason to think that our transit times are wrong...

**Comment by moeckel** [comment]
➤ Carlos Llorca commented:

The file main.html has similar plots for only the selected alternative (1st to 3rd plots).  Then, the amount of points with non-plausible speeds is much lower... 

Also, the second set of plots (4th to 6th) are for trips within Munich.

**Comment by cllorca1** [comment]
Closed, as this is not a MITO issue, but perhaps a data improvement.
