### ISSUE TITLE
[OBUAM] Do not scale down UAM trips

### ISSUE THREAD

**Issue by RRothfeld** [msmobility/mito#59]
From MITO to MATSim, we scale down the trips and road/parking capacities to, e.g., 10%. For UAM, however, scaling down has an issue when it comes to capacity, since how can we scale down to 10% if a vehicle has 4 seats. The same goes for pooling multiple passengers into one vehicle.

Rolf just had the great idea, that we could scale down all non-uam users to not slow down MATSim, but simulate 100% of uam users in order to get valuable information on uam pooling etc.

Let's adjust the MITO-MATSim interface to include a setting for scaling (or not scaling) uam independently of other modes (which remain scaled).

**Comment by cllorca1** [comment]
This is now operational in master-obuam branch.
