### ISSUE TITLE
Fix Scaling in Trip Balancing

### ISSUE THREAD

**Issue by nkuehnel** [msmobility/mito#6]
[from Intellij todo in TripBalancer as of [latest appearance on github](https://github.com/msmobility/mito/blob/6be4ef780f2db9ec470e37eee7a55cee74f852dd/src/main/java/de/tum/bgu/msm/modules/tripGeneration/TripBalancer.java)]

`// adjust attractions (or productions for NHBW and NHBO)
            for (Zone zone : dataSet.getZones().values()) {
                final float attrSumFinal = attrSum;
                tripAttractionByZoneAndPurpose.get(zone.getZoneId()).replaceAll((k, v) -> v * tripsByPurp / attrSumFinal);
            }`

for NHBW and NHBO, we have more confidence in total production, as it is based on the household travel survey. The distribution, however, is better represented by attraction rates. Therefore, attractions are first scaled to productions (step above) and then productions are replaced with zonal level attractions (step below). 
**todo: fix scaling towards attractions. Difficult, because individual households need to give up trips  or add trips to match attractions. Maybe it is alright to rely on productions instead.** 

```
 if (tripPurposes.values()[purp] == tripPurposes.NHBW || tripPurposes.values()[purp] == tripPurposes.NHBO)
                    tripProd[zone][purp][mstmInc] = tripAttractionByZoneAndPurpose[zone][purp][mstmInc];
```

**Comment by moeckel** [comment]
Agreed, this might be the best solution we can do right now. Once we move to an activity-based approach, non-home-based trips will disappear (as they will be integrated in tours). For now, let's scale NHB attractions to NHB productions.
