### ISSUE TITLE
Stop writing skims to disk

### ISSUE THREAD

**Issue by moeckel** [msmobility/mito#66]
By default, MITO should not write out the skim matrix, as everything is handled in memory. When SILO runs with MITO and MATSim, the skims are passed in memory from MATSim via MITO to SILO. 

However, there should be properties option to write out the skim file in OMX format for a specified year. The value of a properties token "write.skim.file" (or something similar) should be "-1" by default to skip writing this file. The user should be able to set it to an array to specify which years the skims shall be written, such as "2020,2030,2050". This setting will always apply to auto and transit skims (if transit is implemented).

Skims should be written to the output directory, using a default skim file name that is extended by "_YEAR.omx".

**Comment by nkuehnel** [comment]
MITO standalone is always for one specific year - wouldn't that mean that this should be set for one specific run only? The option to specify it for multipe years should then be within SILO which creates one-year-instances of MITO. In this case a simple "yes/no" property would be sufficient in MITO

**Comment by moeckel** [comment]
Agreed, a MITO stand-alone model run will always be for one year only. Therefore, you are right that a simple yes/no property is sufficient. I like the idea!
